#ifndef CONFIG_H
#define CONFIG_H
#define CFG_IMAGE_SIZE_MB       20
#define CFG_KERNEL_START_SECTOR 32
#define CFG_KERNEL_MAX_SECTORS  8192
#define CFG_XCFS_META_SECTOR    8224
#define CFG_XCFS_META_SECTORS   1024
#define CFG_XCFS_DATA_SECTOR    9248
#endif
